default: &default
  adapter: sqlite3
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production_default: &production_default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: storage/development.sqlite3


test:
  <<: *default
  database: storage/test.sqlite3


production:
  primary:
    <<: *production_default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *production_default
    url: <%= ENV["DATABASE_URL"] %> # または専用のキャッシュ用DB URL
  cable:
    <<: *production_default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *production_default
    url: <%= ENV["DATABASE_URL"] %>